### ISSUE TITLE
Trying to upload video fails.

### ISSUE THREAD

**Issue by viktorgardart** [thujohn/twitter#159]
When i'm trying to upload [this video](https://s3.amazonaws.com/fanzone-player-content/dbf75003-47cf-4eea-aa85-d79a8a33b280/posts/7027bfca-707f-45f5-b42c-9929e9216190.mp4) i'm getting a 400 response and the tweet is not being posted. 

**Stack trace:**
```
Exception: [400]  in WORKING_DIRECTORY/vendor/thujohn/twitter/src/Thujohn/Twitter/Twitter.php:297
Stack trace:
#0 WORKING_DIRECTORY/vendor/thujohn/twitter/src/Thujohn/Twitter/Twitter.php(321): Thujohn\Twitter\Twitter->query('media/upload', 'POST', Array, true)
#1 WORKING_DIRECTORY/vendor/thujohn/twitter/src/Thujohn/Twitter/Traits/MediaTrait.php(102): Thujohn\Twitter\Twitter->post('media/upload', Array, true)
#2 WORKING_DIRECTORY/app/Jobs/PostJob.php(76): Thujohn\Twitter\Twitter->uploadMediaChunked(Array)
#3 WORKING_DIRECTORY/app/Console/Commands/RunScheduledPosts.php(57): App\Jobs\PostJob->handle()
#4 [internal function]: App\Console\Commands\RunScheduledPosts->handle()
#5 WORKING_DIRECTORY/bootstrap/cache/compiled.php(1248): call_user_func_array(Array, Array)
#6 WORKING_DIRECTORY/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#7 WORKING_DIRECTORY/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 WORKING_DIRECTORY/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 WORKING_DIRECTORY/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 WORKING_DIRECTORY/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\RunScheduledPosts), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 WORKING_DIRECTORY/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 WORKING_DIRECTORY/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 WORKING_DIRECTORY/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  
```

code: 
```php
$file_ext = "." . pathinfo(urlencode($file_url), PATHINFO_EXTENSION);
$file = $this->storeMedia('jdsakajd', $file_ext, $file_url); // This is a helper function thats is correctly working.

$twitter = Twitter::reconfig(['token' => $twitter_tokens['id'], 'secret' => $twitter_tokens['secret']]);

try {
    $media = $twitter->uploadMediaChunked(['media_file' => $file]);
    $twitter->postTweet(["status" => $content["caption"], 'media_ids' => [$media->media_id_string]]);
}catch(Exception $e) {
    Log::error("upload twitter media failed: " . $e->getMessage());
    exit;
}
```

Edit: 
Uploading [this video](https://s3.amazonaws.com/fanzone-player-content/dbf75003-47cf-4eea-aa85-d79a8a33b280/posts/1068dcd2-ed03-4f37-a8cb-dd9cff91b559.mp4) works correctly. 
Looking at the encoding I can se no difference on them :/

**Comment by viktorgardart** [comment]
Ping @thujohn

**Comment by viktorgardart** [comment]
@thujohn Do you still maintain this repo?

**Comment by viktorgardart** [comment]
Can also add that if i'm doing a `dd(Twitter::logs());` it's just an empty array!

**Comment by viktorgardart** [comment]
Decided to change library.

**Comment by samcambridge** [comment]
@viktorgardart which library have you switched too?

**Comment by viktorgardart** [comment]
@samcambridge [jublonet/codebird-php](http://github.com/jublonet/codebird-php)

**Comment by scottybo** [comment]
Just in case someone else finds this thread, I've forked this package and added video support (docs for video near the bottom of the readme): https://github.com/scottybo/twitter

**Comment by FrankChinedu** [comment]
@scottybo i tried upload video but it through 400 exception

**Comment by m7ammad7assan** [comment]
I am facing this issue, I think this package cannot upload video to Twitter in docs he said (images) only
